# Configuración del servidor Nginx
server {
    # El servidor escucha en el puerto 80 para recibir tráfico HTTP.
    listen       80;
    
    # Define el nombre del servidor como localhost.
    server_name  localhost;

    # Define el directorio raíz donde se encuentran los archivos estáticos.
    root /usr/share/nginx/html;
    
    # Especifica el archivo de índice predeterminado.
    index index.html;

    # Configuración para manejar las solicitudes a la ruta /sed-front/.
    location /sed-front/ {
        # Intenta servir el archivo solicitado, y si no existe, redirige a /sed-front/index.html.
        try_files $uri $uri/ /sed-front/index.html;
    }

    # Redirige las solicitudes a /sed-front sin la barra final a /sed-front/.
    location = /sed-front {
        return 301 /sed-front/;
    }

    # Define una página personalizada para errores del servidor (500, 502, 503, 504).
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        # Especifica el directorio raíz para la página de error.
        root /usr/share/nginx/html;
    }
}


